### ISSUE TITLE
Issue with PDF

### ISSUE THREAD

**Issue by cur3n4** [gheeres/PDFSharp.Extensions#1]
Hello,
First of all thanks for the great library, it is excellent and very useful.
I have found that sometimes the image PDFDictionary, contains an element for "Filter" which is actually a PDFArray with a single element.
This causes an error as the PDFDictionaryExtension#ToImage method calls <code>dictionary.Elements.GetName("/Filter")</code> which fails if the element is a PDFArray.
I cannot attach a sample PDF as it contains sensitive information, but I you are very interested I can try to generate one.
I have done a crude modification to PDFDictionaryExtensions to check if the /Filter element is an array, if so then extracts the first element to determine the filter. However I am sure there must be a better way...
Cheers

**Comment by gheeres** [comment]
Yes, please attach / send an example.

**Comment by cur3n4** [comment]
Emailed it to you.

**Comment by gheeres** [comment]
Thanks. I received the file. 

See commit 39e7f4016b0aa019e56cb0ea3242ca7321a92d03

[Nuget package](http://www.nuget.org/packages/PDFSharp.Extensions/) updated & published.
