### ISSUE TITLE
Multiple /Filter support

### ISSUE THREAD

**Issue by gheeres** [gheeres/PDFSharp.Extensions#2]
Moved from commit comments: 39e7f4016b0aa019e56cb0ea3242ca7321a92d03

Hi Georges,

Thanks again for that.

I have found another pdf which fails, the reason seems to be that the RGB
encoded Flat image is not multiple of 3...
(PdfDictionaryExtensions#ConvertRGBStreamToBGR)
This file originally contained iref streams, but then it was saved using
itext# so that it was compatible with 1.4, and reopened it with PDF#
(standard workaround to be able to work with PDFs with iref streams with
PDF#).

Not sure it is something that will normally occur, but just for your info
please see attached pdf.

Cheers and thanks a lot

Sergio

**Comment by gheeres** [comment]
The /Filter for that PDF actually contains:

/FlatDecode
/DCTDecode

Hmm...

/DCTDecode indicates a JPEG image. 
/FlatDecode is zlib/default algorithm.

JPEG already does compression... using /FlatDecode on top likely doesn't yield any additional compression... probably actually a slightly larger file?

The current code doesn't take into account the processing of multiple filters. When I created the library I didn't know it was possible, nor do I know which filter should be applied first, etc. I'll have to read the PDF spec again to see if I can find more information.

**Comment by gheeres** [comment]
See commit: f4cc9fc2f74efeecd0633305411809cc4ec0185c

That handles the processing (for this use case)... however... now you have a new problem. It appears as through the IREF conversion actually generates 5 separate images. 

Below is the code that I used for testing:

``` csharp
  public class Default
  {
    [STAThread]
    static void Main(string[] args)
    {
      string filename = @".\\2f7a95cc-82b3-4934-813b-be7824858791-0.pdf";
      var document = PdfReader.Open(filename);

      int index = 0;
      foreach (var image in document.GetImages()) {
        if (image != null) {
          image.Save(String.Format(".\\EXTRACT-{0:0000}.png", ++index), ImageFormat.Png);
        }
        else Console.WriteLine("NO IMAGES EXTRACTED");
      }
    }
  }
```

**Comment by cur3n4** [comment]
Thanks a lot for that, and yes I realised that. i thought it was an issue
with the iText# conversion, but it seems some other PDF libraries have the
same issue.

Thanks a lot for your help agaom
